language: python
python:
  - "3.6"
  - "3.7-dev" # 3.7 development branch
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install python-coveralls
# command to run tests
script:
  - py.test # or py.test for Python versions 3.5 and below
after_success:
  - coveralls   # uploads reports to coveralls.io